### ISSUE TITLE
Missing decoration and hint

### ISSUE THREAD

**Issue by A7Aima** [shivbo96/otp_pin_field#10]
in otp field I want add the text hint like a dot 
in this u didn't provide any hint field or styling to work on 

plz provide that It would be grateful

Thankyou.

**Comment by shivbo96** [comment]
Hi @A7Aima  you can use **otpPinInputCustom** with **otpPinFieldDecoration** you can archive this. Kindly ref below code 

NOTE:  You can give any character inside **otpPinInputCustom** like *,-,$,# and many more


`Dart
  OtpPinField(
                            onSubmit: (text) {},
                            otpPinInputCustom: '*',
                            otpPinFieldStyle: const OtpPinFieldStyle(),
                            onChange: (text) {},
                            otpPinFieldDecoration: OtpPinFieldDecoration.defaultPinBoxDecoration,
                            otpPinFieldInputType: OtpPinFieldInputType.custom,
                          ),
`
