### ISSUE TITLE
RangeError with maxlength = 6

### ISSUE THREAD

**Issue by joshuamoreno1** [shivbo96/otp_pin_field#11]
**Describe the bug**
Hi I'm getting this error when try to use with a maxlength = 6:

```
flutter: RangeError
flutter: RangeError (index): Invalid value: Not in inclusive range 0..3: 4
```

**To Reproduce**
1. Initialize using this config:

**Expected behavior**
Allow to have 6 digits input.

**Screenshots**
<img width="670" alt="image" src="https://github.com/shivbo96/otp_pin_field/assets/1558591/2d4bfd7b-bf4b-4e55-915c-20b194348685">

**Smartphone (please complete the following information):**
 - Device: Iphone 12
 - OS: 17.2

**Comment by Arun-TechAhead** [comment]
Hi @joshuamoreno1  can you try to stop and re-run your project as Its perfectly fine [use latest-version []](https://pub.dev/packages/otp_pin_field)
Uploading Screen Recording 2024-05-14 at 3.13.40 PM.mov…

**Comment by shivbo96** [comment]
Hi @joshuamoreno1 can you try to stop and re-run your project as Its perfectly fine [use latest-version](https://pub.dev/packages/otp_pin_field)
Uploading Screen Recording
https://github.com/shivbo96/otp_pin_field/assets/21358631/12fe1365-e973-4653-afd1-a4e24e848488

**Comment by joshuamoreno1** [comment]
You are awesome dude, thanks a lot!!!
