### ISSUE TITLE
Clear all text fields at once

### ISSUE THREAD

**Issue by nishantvekariya21** [shivbo96/otp_pin_field#14]
How can I clear all text fields at once while using the "otp_pin_field"?

**Comment by shivbo96** [comment]
> Why does it return this error, when I enable the "autoFillEnable: true" property?

Hello @nishantvekariya21,

When you enable the `autoFillEnable: true` property and encounter an error, it is likely due to missing permissions or not following the required constraints for Android SMS retrieval.

To use the `autoFillEnable` functionality, you need to enable Android SMS constraints. For the code to be received, it must follow certain rules as described in the [Google SMS Retriever API documentation](https://developers.google.com/identity/sms-retriever/verify):

1. The SMS must be no longer than 140 bytes.
2. It must contain a one-time code that the client sends back to your server to complete the verification flow.
3. It should end with an 11-character hash string that identifies your app.

An example of a valid SMS would be:
```
8125 is your verification code Ov114rXIhwf
```
In this example, `Ov114rXIhwf` is the hash value, which you will get in the log. Search for `your hash value is` in the log and append that value in your SMS.

Additionally, you need to add the following permissions to your Android manifest file:
```xml
<uses-permission android:name="android.permission.READ_SMS"/>
<uses-permission android:name="android.permission.RECEIVE_SMS"/>
```

By ensuring these constraints and permissions are met, you should be able to use the `autoFillEnable` property without issues.

Best regards,  
Shivam Mishra

**Comment by shivbo96** [comment]
> > Hello @nishantvekariya21 ,
> > To clear all text fields at once while using the "otp_pin_field" package, you can utilize the `_otpPinFieldController` controller.
> > First, declare the controller as follows:
> > ```dart
> > final _otpPinFieldController = GlobalKey<OtpPinFieldState>();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Next, ensure you pass this key to your `OtpPinField` widget:
> > ```dart
> > OtpPinField(
> >   key: _otpPinFieldController,
> >   // other properties
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To clear the OTP fields, use the following line of code from the desired location:
> > ```dart
> > _otpPinFieldController.currentState?.clearOtp();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will effectively clear all the text fields at once.
> > Best regards, Shivam Mishra
> 
> Once I clear all the text fields again I can't type anything (the keyboard doesn't open to type).

Hello @nishantvekariya21,

The issue where the keyboard does not open to type after clearing all text fields has been resolved in the new version 1.2.6 of the package. Please update to the latest version to resolve this issue.

Best regards,

**Comment by shivbo96** [comment]
Hello @nishantvekariya21,

To give only the bottom border to all text fields, you can use the `OtpPinFieldDecoration.underlinedPinBoxDecoration` along with the `defaultFieldBorderColor` and `activeFieldBorderColor` properties in the `otpPinFieldStyle`.

Here is an example code snippet to achieve this:

```dart
OtpPinField(
  key: _otpPinFieldController,

  /// In case you want to enable autoFill
  autoFillEnable: false,

  /// For iOS it is not needed as the SMS autofill is provided by default,
  /// but not for Android, that's where this key is useful.
  textInputAction: TextInputAction.done,

  /// In case you want to change the action of keyboard
  /// to clear the Otp pin Controller
  onSubmit: (text) {
    print('Entered pin is $text');
    /// Return the entered pin
  },
  onChange: (text) {
    print('Entered on change pin is $text');
    /// Return the entered pin
  },
  onCodeChanged: (code) {
    print('onCodeChanged is $code');
  },

  /// To decorate your Otp_Pin_Field
  otpPinFieldStyle: OtpPinFieldStyle(
    /// Border color for inactive/unfocused Otp_Pin_Field
    defaultFieldBorderColor: Colors.red,

    /// Border color for active/focused Otp_Pin_Field
    activeFieldBorderColor: Colors.indigo,
  ),
  maxLength: 4,

  /// Number of pin fields
  showCursor: true,

  /// Boolean to show cursor in pin field or not
  cursorColor: Colors.indigo,

  /// To select cursor width
  cursorWidth: 3,

  /// Place otp pin field according to yourself
  mainAxisAlignment: MainAxisAlignment.center,

  /// Predefine decorate of pinField use OtpPinFieldDecoration.defaultPinBoxDecoration ||
  /// OtpPinFieldDecoration.underlinedPinBoxDecoration ||
  /// OtpPinFieldDecoration.roundedPinBoxDecoration
  /// Use OtpPinFieldDecoration.custom (by using this you can make Otp_Pin_Field according to yourself 
  /// like you can give fieldBorderRadius, fieldBorderWidth and other properties)
  otpPinFieldDecoration: OtpPinFieldDecoration.underlinedPinBoxDecoration,
)
```

By using the above code, you can ensure that each text field in the OTP pin field will have only the bottom border.

Best regards,  
Shivam Mishra

**Comment by shivbo96** [comment]
Hello @nishantvekariya21,

No, you cannot directly use the `border: Border(bottom: BorderSide(width: 1.5, color: Colors.grey[300]))` property in the current implementation of the `otp_pin_field` package. However, you can achieve a similar effect by setting the same color for `defaultFieldBorderColor` and `activeFieldBorderColor`, and specifying `fieldBorderWidth` as 1.5.

Additionally, please update your library to the latest version, as I have made some changes to make the library more useful for you.

Here is an example code snippet to achieve the desired border effect:

```dart
OtpPinField(
  key: _otpPinFieldController,

  /// In case you want to enable autoFill
  autoFillEnable: false,

  /// For iOS it is not needed as the SMS autofill is provided by default,
  /// but not for Android, that's where this key is useful.
  textInputAction: TextInputAction.done,

  /// In case you want to change the action of keyboard
  /// to clear the Otp pin Controller
  onSubmit: (text) {
    print('Entered pin is $text');
    /// Return the entered pin
  },
  onChange: (text) {
    print('Entered on change pin is $text');
    /// Return the entered pin
  },
  onCodeChanged: (code) {
    print('onCodeChanged is $code');
  },

  /// To decorate your Otp_Pin_Field
  otpPinFieldStyle: OtpPinFieldStyle(
    /// Border color for inactive/unfocused Otp_Pin_Field
    defaultFieldBorderColor: Colors.grey[300],

    /// Border color for active/focused Otp_Pin_Field
    activeFieldBorderColor: Colors.grey[300],

    /// Border width
    fieldBorderWidth: 1.5,
  ),
  maxLength: 4,

  /// Number of pin fields
  showCursor: true,

  /// Boolean to show cursor in pin field or not
  cursorColor: Colors.indigo,

  /// To select cursor width
  cursorWidth: 3,

  /// Place otp pin field according to yourself
  mainAxisAlignment: MainAxisAlignment.center,

  /// Predefine decorate of pinField use OtpPinFieldDecoration.defaultPinBoxDecoration ||
  /// OtpPinFieldDecoration.underlinedPinBoxDecoration ||
  /// OtpPinFieldDecoration.roundedPinBoxDecoration
  /// Use OtpPinFieldDecoration.custom (by using this you can make Otp_Pin_Field according to yourself 
  /// like you can give fieldBorderRadius, fieldBorderWidth and other properties)
  otpPinFieldDecoration: OtpPinFieldDecoration.underlinedPinBoxDecoration,
)
```

By using the above code, you can ensure that each text field in the OTP pin field will have the desired bottom border with the specified color and width.

Best regards,  
Shivam Mishra

**Comment by shivbo96** [comment]
Hello @nishantvekariya21,

When using `otpPinFieldDecoration: OtpPinFieldDecoration.underlinedPinBoxDecoration`, the `borderRadius` property does not work. To utilize `borderRadius`, you need to use `otpPinFieldDecoration: OtpPinFieldDecoration.custom`.

Additionally, I have added some box border functionality in the new version. Please upgrade your package to version `1.2.8` to take advantage of these new features. You can find the latest version [here](https://pub.dev/packages/otp_pin_field).

Here is an example Dart code snippet demonstrating how to use the custom decoration with the new box border functionality. Remember to replace the color with your desired color:

```dart
OtpPinField(
  key: _otpPinFieldController,
  textInputAction: TextInputAction.done,
  onSubmit: (text) {
    print('Entered pin is $text');
  },
  onChange: (text) {
    print('Entered on change pin is $text');
  },

  // To decorate your Otp_Pin_Field
  otpPinFieldStyle: OtpPinFieldStyle(
    defaultFieldBackgroundColor: Colors.white,
    activeFieldBackgroundColor: Colors.white,
    filledFieldBackgroundColor: Colors.white,
    fieldBorderWidth: 1,
    fieldBorderRadius: 10,
    activeFieldBoxShadow: [
      BoxShadow(
        color: Colors.blue.withOpacity(0.8),
        offset: Offset(0, 3),
      ),
    ],
    filledFieldBoxShadow: [
      BoxShadow(
        color: Colors.blue.withOpacity(0.5),
        offset: Offset(0, 3),
      ),
    ],
    defaultFieldBoxShadow: [
      BoxShadow(
        color: Colors.blue.withOpacity(0.5),
        offset: Offset(0, 3),
      ),
    ],
  ),
  maxLength: 4,
  cursorColor: Colors.blue.withOpacity(0.8),
  cursorWidth: 3,
  mainAxisAlignment: MainAxisAlignment.center,
  otpPinFieldDecoration: OtpPinFieldDecoration.custom,
)
```

By upgrading to version `1.2.8` and using the `custom` decoration, you can fully utilize the `borderRadius` property along with the new box border functionality.

Best regards,  
Shivam Mishra

<img width="421" alt="Screenshot 2024-07-04 at 4 58 30 PM" src="https://github.com/shivbo96/otp_pin_field/assets/37922543/090facff-5f41-468f-8735-e0cff40f4f4a">

**Comment by shivbo96** [comment]
Hello @nishantvekariya21,

When using `otpPinFieldDecoration: OtpPinFieldDecoration.underlinedPinBoxDecoration`, the `borderRadius` property does not work. To utilize `borderRadius`, you need to use `otpPinFieldDecoration: OtpPinFieldDecoration.custom`.

Additionally, the error you're encountering with the parameter `activeFieldBoxShadow` not being defined can usually be resolved by clearing your cache and ensuring you are using the latest updated package.

Please try the following steps:
1. Run `flutter clean` in your terminal.
2. Run `flutter pub get` to reinstall dependencies.

Regarding your suggestion to add a border parameter for easier customization, we appreciate your feedback and will consider it for future updates. Stay tuned for upcoming features!

For now, you can use the following Flutter code:

```dart
OtpPinField(
  key: _otpPinFieldController,
  textInputAction: TextInputAction.done,
  onSubmit: (text) {
    print('Entered pin is $text');
  },
  onChange: (text) {
    print('Entered on change pin is $text');
  },

  // To decorate your Otp_Pin_Field
  otpPinFieldStyle: OtpPinFieldStyle(
    defaultFieldBackgroundColor: Colors.white,
    activeFieldBackgroundColor: Colors.white,
    filledFieldBackgroundColor: Colors.white,
    fieldBorderWidth: 1,
    fieldBorderRadius: 10,
    activeFieldBoxShadow: [
      BoxShadow(
        color: Colors.blue.withOpacity(0.8),
        offset: Offset(0, 3),
      ),
    ],
    filledFieldBoxShadow: [
      BoxShadow(
        color: Colors.blue.withOpacity(0.5),
        offset: Offset(0, 3),
      ),
    ],
    defaultFieldBoxShadow: [
      BoxShadow(
        color: Colors.blue.withOpacity(0.5),
        offset: Offset(0, 3),
      ),
    ],
  ),
  maxLength: 4,
  cursorColor: Colors.blue.withOpacity(0.8),
  cursorWidth: 3,
  mainAxisAlignment: MainAxisAlignment.center,
  otpPinFieldDecoration: OtpPinFieldDecoration.custom,
)
```

Please update your library to the latest version (`otp_pin_field: ^1.2.8`) to take advantage of the new features and improvements. You can find the latest version [here](https://pub.dev/packages/otp_pin_field).

Best regards,  
Shivam Mishra

**Comment by poorankharol** [comment]
Once I clear all the text fields again I can't type anything (the keyboard doesn't open to type).
