### ISSUE TITLE
Flutter Web AutoFocus Disabled

### ISSUE THREAD

**Issue by vincekruger** [shivbo96/otp_pin_field#21]
**Describe the bug**
AutoFocus on web is disabled: https://github.com/shivbo96/otp_pin_field/blob/423d0f3cdb67bcf3cf64328aa00440e97ba309ec/lib/src/otp_pin_field_state.dart#L199

Any reason?

**Comment by shivbo96** [comment]
Hi @vincekruger ,

Thank you for your question!

The reason autofocus is disabled on the web (autofocus: !kIsWeb ? widget.autoFocus : false) is to prevent potential issues with how some web browsers handle autofocus. In certain cases, enabling autofocus on the web can cause inconsistent behavior, such as the field not receiving focus properly or affecting the overall user experience (e.g., scrolling or zooming issues when the input field is focused automatically).

However, if autofocus is crucial for your web use case, we can explore ways to make it configurable or find a more web-friendly solution. Let me know if you'd like further assistance or if you have additional insights!

Best regards,

**Comment by shivbo96** [comment]
Hi @vincekruger  ,

Thank you all for your feedback and for reporting the issues. I’m happy to inform you that the following issues have been resolved:

- **SMS hint autofill issue** when `autoFillEnabled == false` has been fixed.
- **Autofocus issue on the web** is now resolved, and autofocus works as expected.
- **New hint text feature** has been added, allowing you to customize `showHintText`, `hintText`, and `hintTextColor`.

You can now update to version **1.3.0** of the package, available here: [otp_pin_field v1.3.0](https://pub.dev/packages/otp_pin_field).

Thanks again for your contributions and patience! Let me know if you encounter any further issues.

Best regards,
