### ISSUE TITLE
Keyboard gets dismissed when first character is typed in

### ISSUE THREAD

**Issue by Jayasubin** [shivbo96/otp_pin_field#23]
**Describe the bug**
I have the `otp_pin_field` with autofocus enabled, on an `AlertDialog` in my app. On android, when I start typing and enter the first digit of my OTP, the keyboard closes itself.

**To Reproduce**
Visit the page with the pin-field
Focus it (or even if it is auto focused)
Type one character

The keyboard gets dismissed immediately.
When you click on the second box and continue typing, that part doesn't have this issue

**Expected behavior**
The second box should get focused as usual

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Android Phone
 - OS: Xiaomi HyperOs 1.0.6.0 - android 14

**Additional context**
We test on four different phones (with different android versions). only this one has this issue.

There is a "autofill from SMS" button appearing above the keyboard (only on the first character is focused) would that cause this issue?

**Comment by shivbo96** [comment]
Hi @Jayasubin ,

Thank you all for your feedback and for reporting the issues. I’m happy to inform you that the following issues have been resolved:

SMS hint autofill issue when autoFillEnabled == false has been fixed.
Autofocus issue on the web is now resolved, and autofocus works as expected.
New hint text feature has been added, allowing you to customize showHintText, hintText, and hintTextColor.
You can now update to version 1.3.0 of the package, available here: [otp_pin_field v1.3.0](https://pub.dev/packages/otp_pin_field).

Thanks again for your contributions and patience! Let me know if you encounter any further issues.

Best regards,

**Comment by shivam0139** [comment]
Hi  @Jayasubin ,

We’ve addressed the keyboard dismissal issue for now and are marking this as resolved. If you encounter any similar issues or if the problem persists, feel free to reach out, and we’ll be happy to investigate further.

Thank you for your patience and for helping us improve the package!

**Comment by shivbo96** [comment]
Hi @Jayasubin ,

We’ve addressed the keyboard dismissal issue for now and are marking this as resolved. If you encounter any similar issues or if the problem persists, feel free to reach out, and we’ll be happy to investigate further.

Thank you for your patience and for helping us improve the package!
