### ISSUE TITLE
SMS Hint Issue

### ISSUE THREAD

**Issue by MSL-BIT** [shivbo96/otp_pin_field#24]
**Describe the bug**
We see the SMS hint although we set the flag to false

**To Reproduce**
1. Setup the OtpPinField() with autoFillEnabled == false and smsRegex == null

**Expected behavior**
User can type the pin without a hint. 

**Screenshots**
<img width="577" alt="image" src="https://github.com/user-attachments/assets/d58557e3-04ed-4656-8be8-406e74271eb5">

**Comment by MSL-BIT** [comment]
Seems to be an issue with:
```
autofillHints: const [AutofillHints.oneTimeCode]
```
should be `null` when autoFillEnabled == false

**Comment by shivbo96** [comment]
Hi @MSL-BIT ,

Thank you for reporting this issue and for your insights!

It looks like you're right. The autofillHints should indeed be set to null when autoFillEnabled == false to prevent the SMS hint from showing. I’ll make the necessary adjustments in the OtpPinField implementation to ensure that when autoFillEnabled is set to false, the autofillHints will be disabled properly.

I'll work on this and get back to you with a fix soon. If you have any more details or suggestions, feel free to share!

Cheers

**Comment by MSL-BIT** [comment]
Hi @shivbo96 
Thanks for your reply. 

Can you estimate when you will have a chance to add this fix? 
Otherwise I can also raise a PR. 

Cheers

**Comment by MSL-BIT** [comment]
I have no access access rights to create a branch and raise a pull request. 
Here my suggestion, for both appearances:

 autofillHints: (widget.autoFillEnable ?? false) ? const [AutofillHints.oneTimeCode] : [],

**Comment by shivbo96** [comment]
Hi @MSL-BIT ,

Thank you all for your feedback and for reporting the issues. I’m happy to inform you that the following issues have been resolved:

- **SMS hint autofill issue** when `autoFillEnabled == false` has been fixed.
- **Autofocus issue on the web** is now resolved, and autofocus works as expected.
- **New hint text feature** has been added, allowing you to customize `showHintText`, `hintText`, and `hintTextColor`.

You can now update to version **1.3.0** of the package, available here: [otp_pin_field v1.3.0](https://pub.dev/packages/otp_pin_field).

Thanks again for your contributions and patience! Let me know if you encounter any further issues.

Best regards,
